# Generated by Django 6.0.2 on 2026-02-28 21:58
import os

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from dotenv import load_dotenv

load_dotenv()


def create_default_admin(apps, schema_editor):
    User = apps.get_model(
        settings.AUTH_USER_MODEL.split('.')[0],
        settings.AUTH_USER_MODEL.split('.')[1],
    )

    username = "admin"
    email = "admin@example.com"
    password = os.getenv("ADMIN_PASSWORD")

    if not User.objects.filter(username=username).exists():
        User.objects.create_superuser(
            username=username, email=email, password=password
        )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'encryption_salt',
                    models.CharField(
                        max_length=64, verbose_name='Salt (base64)'
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profile',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.RunPython(
            create_default_admin,
        ),
    ]
