# Generated by Django 6.0.2 on 2026-03-12 00:01

import django.db.models.deletion
import sharing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedAccess',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'token',
                    models.CharField(
                        db_index=True,
                        default=sharing.models._generate_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    'data_blob',
                    models.TextField(
                        verbose_name='Данные (шифротекст или JSON)'
                    ),
                ),
                ('is_encrypted', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='shared_accesses',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Общий доступ',
                'verbose_name_plural': 'Общие доступы',
                'ordering': ['-created_at'],
            },
        ),
    ]
