# Generated by Django 6.0.2 on 2026-02-28 21:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def create_default_tags(apps, schema_editor):
    Tag = apps.get_model("entries", "Tag")

    tag_names = [
        "Работа",
        "Семья",
        "Спорт",
        "Отдых",
        "Стресс",
    ]

    for name in tag_names:
        Tag.objects.get_or_create(name=name)


def reverse_default_tags(apps, schema_editor):
    Tag = apps.get_model("entries", "Tag")

    tag_names = [
        "Работа",
        "Семья",
        "Спорт",
        "Отдых",
        "Стресс",
    ]

    Tag.objects.filter(name__in=tag_names).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(create_default_tags, reverse_default_tags),
        migrations.CreateModel(
            name="MoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mood",
                    models.TextField(verbose_name="Настроение (зашифровано)"),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Заметка (зашифровано)",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата и время",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mood_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="entries",
                        to="entries.tag",
                        verbose_name="Теги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="entries_moo_user_id_d26c5a_idx",
                    )
                ],
            },
        ),
    ]
