# Generated by Django 6.0.2 on 2026-03-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moodentry",
            name="anxiety",
            field=models.TextField(
                blank=True, default="", verbose_name="Тревога (зашифровано)"
            ),
        ),
    ]
