# Generated by Django 6.0.2 on 2026-08-08 12:40

import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_user_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='moodentry',
            index=models.Index(django.db.models.functions.datetime.TruncDate('timestamp'), models.F('user'), name='entry_user_day_idx'),
        ),
    ]
